### ISSUE TITLE
Callback issue

### ISSUE THREAD

**Issue by 24THEGuNNeR07** [epinna/Stegosip#3]
Hi,
i receive following:
error TypeError: cb() takes exactly 3 arguments (2 given)
callback failure !
What can be a problem ?

**Comment by 24THEGuNNeR07** [comment]
Ok after removing i parameter from _cb_ function script works fine.

**Comment by epinna** [comment]
Thanks, would you please submit a PR with the fix?

**Comment by epinna** [comment]
Merged, thanks.
